### ISSUE TITLE
TypeScript compiler failed with exit code 1

### ISSUE THREAD

**Issue by RainingNight** [NativeScript/sample-ng-todomvc#5]
Executing before-prepare hook from c:\Users***\Source\Local\NativeScript\sample-ng-todomvc\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 1.8.2
node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.

TypeScript compiler failed with exit code 1
Sending exception report (press Ctrl+C to stop).......

**Comment by vabatta** [comment]
+1

**Comment by AlexandreKilian** [comment]
it's not a fix, but you can comment out and it'll run

**Comment by VladimirAmiorkov** [comment]
This started happening in my projects today. Very strange as such errors did not causes compiler error but were only outputted as errors.

**Comment by VladimirAmiorkov** [comment]
I feel stupid, I had `"noEmitOnError": true` in the tsconfig.json :). After setting it to false all is ok.

**Comment by dtopuzov** [comment]
Can not reproduce with latest {N}.
Currently dependencies are a bit out dated, so those are the steps to run the sample:

```
git clone https://github.com/NativeScript/sample-ng-todomvc
cd sample-ng-todomvc
tns plugin remove nativescript-angular
tns plugin add nativescript-angular
tns run android
```

**Comment by camerontbelt** [comment]
I also had the same issue. Just installed a few days ago and finally got around to trying it out, then this happened.
