### ISSUE TITLE
Using this project with tns livesync

### ISSUE THREAD

**Issue by lf-alves** [NativeScript/sample-ng-todomvc#7]
Hello, 

I've been looking around for a good integration of Angular2 and Nativescript and this seems to be the best one around so far. Once set up, I tried running the command tns livesync ios --emulator --watch so I could start messing with it. The problem is, each little change I make to the code takes up to like 15-17 seconds to be applied on the emulator. Any idea why? Livesync has worked perfectly before with normal nativescript projects. I know that the typescript compiler needs to run and compile everything down to js but it shouldn't take this long imo. Can anyone help me with that?

**Comment by dtopuzov** [comment]
Can you please try {N} 2.1.1, it should be faster.

**Comment by dtopuzov** [comment]
Latest {N} include some improvements, especially when live-sync css, xml, html.
Currently this app is a bit outdated and can not get benefit of those improvements, but we will update it soon.
If you want to see the real speed of livesync on Angular projects please try:

```
tns create TestApp --ng
tns run android
tns livesync ios --emulator --watch
```

Notes: 
First time livesync can be a bit slower, but after that it is faster.
Livesync is almost instant for changes in css, xml, html. For *.ts it is a bit slower (~10-12 sec on my mac old mini).
